title: "Connor Marrs"
description: "Mathematics Graduate Student at UC Santa Barbara"

# Enable remote theme
remote_theme: jekyll/minima

# REQUIRED: load the remote theme plugin
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

url: "https://connormarrs.github.io"
baseurl: "/academic-website"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

github_username: connormarrs
