# Site settings
title: "Connor Marrs"
description: "Mathematics Graduate Student at UC Santa Barbara"

# Remote theme instead of local gems
remote_theme: jekyll/minima

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# URL and baseurl
url: "https://connormarrs.github.io"
baseurl: "/academic-website" # IMPORTANT for project sites!

# Markdown settings for math
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Optional social links
github_username: connormarrs

